//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PizzaMaker
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataOrder
    {
        public int id { get; set; }
        public string Name { get; set; }
        public string Contact { get; set; }
        public string OrderType { get; set; }
        public string PizzaName { get; set; }
        public string Qty { get; set; }
        public string Bill { get; set; }
    }
}
